name: "export"

on: ["push", "pull_request"]

jobs:
  export:
    runs-on: "ubuntu-latest"
    container: "barichello/godot-ci:3.2.2"

    strategy:
      matrix:
        include:
          - build: "Windows Desktop"
            output_name: "game.exe"
          - build: "Linux_X11"
            output_name: "game.x86_64"
    
    steps:
    - uses: "actions/checkout@v2"
    
    - name: "setup export"
      run: "mkdir -p ~/build ~/.local/share/godot/templates && mv /root/.local/share/godot/templates/3.2.2.stable ~/.local/share/godot/templates/3.2.2.stable"
    
    - name: "export project"
      run: "godot --export \"${{matrix.build}}\" ~/build/${{matrix.output_name}}"
      working-directory: ${{env.GITHUB_WORKSPACE}}
    
    - uses: "actions/upload-artifact@v2"
      with:
        name: ${{matrix.build}}
        path: "~/build"
